kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ .Values.database.name }}
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.database.name }}-selector
  template:
    metadata:
      labels:
        app: {{ .Values.database.name }}-selector
    spec:
      containers:
        - name: {{ .Values.database.name }}-cont
          image: bitnami/postgresql:15
          ports:
            - name: {{ .Values.database.name }}-tcp
              containerPort: {{ .Values.database.port }}
          volumeMounts:
            - name: {{ .Values.database.name }}-init-volume
              mountPath: /docker-entrypoint-initdb.d/
          envFrom:
            - configMapRef:
                name: {{ .Values.database.name }}-config
            - secretRef:
                name: {{ .Values.database.name }}-secret
          resources:
            {{- toYaml .Values.database.resources | nindent 12 }}
      volumes:
        - name: {{ .Values.database.name }}-init-volume
          configMap:
            name: {{ .Values.database.name }}-init-config
  serviceName: {{ .Values.database.name }}
